### ISSUE TITLE
"Error: plugin "videoJsResolutionSwitcher" does not exist"

### ISSUE THREAD

**Issue by ssqsunqin** [bariartz/videojs-resolution-switcher-for-videojs-version-7#2]
大神，，这个问题是什么原因呢，，插件找不到呢
plugins: {
                // videoJsResolutionSwitcher: {
                //   dynamicLabel: true,
                //   default: 'high'
                // }
              },

**Comment by mzulkiakbari** [comment]
This is a demo : https://bariartz.github.io/videojs-by-pp/

This is example code :
<!doctype html>
<html>
<head>

    <meta charset="utf-8">
<meta name="robots" content="noindex">
    <title>OM Demo</title>
    
    <link href="video-js.css" rel="stylesheet">
    <link href="videojs/plugin/frame/videojs-frame.css" rel="stylesheet">
    <link href="videojs-resolution-switcher.css" rel="stylesheet">

</head>
<style>
  #pokoplayer {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;
}

/* Add some content at the bottom of the video/page */
.content {
    position: fixed;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    color: #f1f1f1;
    width: 100%;
    padding: 20px;
}

button:focus {
  outline:none;
  box-shadow: none;
}

video:focus {
  outline:none;
  box-shadow: none;
}
    
    .video-js .vjs-duration,
.vjs-no-flex .vjs-duration {
  display: block;
}

.video-js .vjs-current-time,
.vjs-no-flex .vjs-current-time {
  display: block;
}

.video-js .vjs-remaining-time,
.vjs-no-flex .vjs-current-time {
  display: none;
}

.vjs-live .vjs-time-control {
  display: block;
}

.vjs-time-divider {
  display: block;
}
  </style>
<body>
                <video id="pokoplayer" class="video-js pkplayer"></video>
                <script src="//vjs.zencdn.net/7.7.4/video.min.js"></script>
                <script src="videojs-resolution-switcher.js"></script>
                <script src="videojs/plugin/frame/videojs-frame.js"></script>

    <script>
        var PkPlayer = videojs('pokoplayer',{
          "controls" : true,
          "autoplay" : true,
          "preload" : "metadata",
          "width" : "100%",
          "height" : "auto",
          "poster" : "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg",
          sources : [
          { src : 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', type : 'video/mp4', label : '360p', res: '360'},
      { src : 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', type : 'video/mp4', label : '480p', res: '480'},
      { src : 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', type : 'video/mp4', label : '720p', res: '720'}
          ],
        });
        videojs('pokoplayer').videoJsResolutionSwitcher();
    </script>

</body>
</html>
