### ISSUE TITLE
videojs.getComponent is not a function

### ISSUE THREAD

**Issue by ssqsunqin** [bariartz/videojs-resolution-switcher-for-videojs-version-7#3]
vue_中添加宰割插件

import 'videojs-resolution-switcher'  导入后就会报videojs.getComponent方法找不到，，大神，在vue中应该怎么导入插件呢

**Comment by linlinjie** [comment]
你是不是引入顺序不对，要先引入videojs，再引入插件js

**Comment by tungtm-unica** [comment]
I am getting the same error, videojs 7, here is my import order

![image](https://user-images.githubusercontent.com/101539988/170932509-09bcf4cb-78eb-43eb-ac0b-d702fd5eed54.png)

**Comment by mzulkiakbari** [comment]
videojs must version 7+
