### ISSUE TITLE
playback pauses on resolution change

### ISSUE THREAD

**Issue by Bruno86** [bariartz/videojs-resolution-switcher-for-videojs-version-7#8]
When resolution change, the player pauses.
solution  i finded is to add a little code in videojs-resolution-switcher.js (line 177) :
``` 
    player
          .setSourcesSanitized(sources, label, customSourcePicker || settings.customSourcePicker)
          .one(handleSeekEvent, function() {
            player.currentTime(currentTime);
            if (!isPaused && player.paused()) {
              player.play()
            }
            player.trigger('resolutionchange');
          });
```
Can you try this code plz ?

**Comment by mzulkiakbari** [comment]
Ok

**Comment by Bruno86** [comment]
Thanks a lot! 
Can you upgrade version and udpate npm package please?

**Comment by mzulkiakbari** [comment]
ya, when i have free time, i will to update npm package. Thank for your contribution. Can i added you as contributor?

**Comment by Bruno86** [comment]
Thank.

> Can i added you as contributor?

Yes you can ;)
